### ISSUE TITLE
how to run the miner?

### ISSUE THREAD

**Issue by xxb** [tromp/equihash#1]
how to run the miner?

**Comment by tromp** [comment]
It's now integrated in Zcash beta RC2. See the beta guide for how to run it.

**Comment by ghost** [comment]
Dear tromp,
  Is headernonce in equi_miner.cpp concatenates block header in this order :
  version(4bytes) + hashPrev(32) + hashMerkleRoot(32) + hashReserved(32) + time(4) + nBits(4) + nonce(32)
?

**Comment by tromp** [comment]
My solver only makes the following assumptions about the header:

it has length 140 bytes.
the 4 bytes at 128,129,130,131 are part of the nonce field.

you can pass any 140 header to my solver and it will try a range of nonce by changing those 4 bytes.

**Comment by ghost** [comment]
Thx for reply
