### ISSUE TITLE
Porting on SPARC?

### ISSUE THREAD

**Issue by ghost** [tromp/equihash#11]
Hello there,
is it possible to have a porting on SPARC CPU?

Here the cpucaps:
lush,stbar,swap,muldiv,v9,blkinit,n2,mul32,div32,fsmuld,v8plus,popc,vis,vis2,ASIBlkInit,fmaf,vis3,hpc,ima,pause,cbcond,adp,vis3b,pause-nsec,mwait,sparc5,vamask,aes,des,camellia,md5,sha1,sha256,sha512,mpmul,montmul,montsqr,crc32c,xmpmul,xmontmul,xmontsqr
Thanks,
Marco

**Comment by tromp** [comment]
dear Marco,

> is it possible to have a porting on SPARC CPU?

The code might just work as is on SPARC. Did you try compiling it?
just try
  make test
in the cloned https://github.com/tromp/equihash repository.
Can you let me know if you run into any errors?

regards,
-John

**Comment by ghost** [comment]
Hi John,
yes I did, but it doesn't work because SPARC CPU does not support SSE or AVX. 

1st error:
g++ -march=native -m64 -std=c++11 -Wall -Wno-deprecated-declarations -D_POSIX_C_SOURCE=200112L -O3 -pthread  -DATOMIC equi_miner.cpp blake/blake2b.cpp -o equi
g++: error: unrecognized command line option ‘-march=native’; did you mean ‘-mcpu=native’?
make: *** [equi] Error 1

I solved it removing " -march=native" from the makefile.

2nd error:
blake/blake2-config.h:68:2: error: #error "This code requires at least SSE2."
 #error "This code requires at least SSE2."
  ^~~~~
blake/blake2b.cpp:23:10: fatal error: emmintrin.h: No such file or directory
 #include <emmintrin.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [equi] Error 1

I tried to compile it inside a LDOM with OracleLinux 6 for SPARC.

Only these capabilities are supported:
flush, stbar, swap, muldiv, v9, blkinit, n2, mul32, div32, fsmuld, v8plus, popc, vis, vis2, ASIBlkInit, fmaf, vis3, hpc, ima, pause, cbcond, adp, vis3b, pause-nsec, mwait, sparc5, vamask, aes, des, camellia, md5, sha1, sha256, sha512, mpmul, montmul, montsqr, crc32c, xmpmul, xmontmul, xmontsqr


Could you help me, please?
Thanks,
Marco

**Comment by tromp** [comment]
Thanks for the bug report, Marco.
I've sent an enquiry about SPARC support to the blake2b authors...

regards,
-John

**Comment by tromp** [comment]
On Sat, Nov 4, 2017 at 7:54 PM, John Tromp <john.tromp@gmail.com> wrote:
> Thanks for the bug report, Marco.
> I've sent an enquiry about SPARC support to the blake2b authors...

Apparently I only included the sse2 blake implementation in my repo.
This means some nontrivial changes will be required to make my solver
run on SPARC.
Without access to a SPARC machine, it's a little hard for me to figure
exactly what is needed.

I would start by copying the three blake files from
https://github.com/tromp/cuckoo/tree/master/src
and rewrite equi_miner.h to use those.

So replace lines 41-73 with
 #include "blake2.h"
 typedef blake2b_state blake_state;

and compile with blake/blake2b.cpp in the Makefile target replaced by
blake2b-ref.c

Then probably you need to tell me how it all still fails:-(

regards,
-John

**Comment by ghost** [comment]
ok! I compiled it successfully. How can I be sure results are identical if I run the program on both x86 and sparc?

Thanks,
Marco

**Comment by tromp** [comment]
dear Marco,

> ok! I compiled it successfully.

Wow; didn't think it would be all that easy.

> How can I be sure results are identical if I
> run the program on both x86 and sparc?

Do you get identical solutions when running with the same header and nonce?

regards,
-John

**Comment by ghost** [comment]
well, I don't know very well your code.. could you, please help me to run this test?

**Comment by tromp** [comment]
dear Marco,

> well, I don't know very well your code.. could you, please help me to run
> this test?

For instance, run
  ./equi1 -h "" -n 0 -t 1 -s

This should give you the output

Looking for wagner-tree on ("0x...",0) with 10 20-bit digits and 1 threads
Using 2^10 buckets, 145MB of memory, and 1-way blake2b
Digit 0 b0 h0
Digit 1 b0 h0
Digit 2 b0 h0
Digit 3 b0 h6
Digit 4 b0 h13
Digit 5 b0 h26
Digit 6 b0 h64
Digit 7 b0 h152
Digit 8 b0 h318
Digit 9
Solution 58d 180768 ... 1ae61b
Solution 35c 12d31f ... 17fbfb

(I shortened the Solution lines because they're really long)

regards,
-John

**Comment by ghost** [comment]
Sorry for my delay... well I tried to compile on sparc and I got this error:

g++ -m64 -std=c++11 -Wall -Wno-deprecated-declarations -D_POSIX_C_SOURCE=200112L -O3 -pthread -DATOMIC equi_miner.cpp blake/blake2b-ref.c -o equi
In file included from equi_miner.h:36:0,
                 from equi_miner.cpp:4:
equi.h:11:20: fatal error: endian.h: No such file or directory
compilation terminated.
*** Error code 1
make: Fatal error: Command failed for target `equi'

I commented the include of endian.h and now I have the errors:

g++ -m64 -std=c++11 -Wall -Wno-deprecated-declarations -D_POSIX_C_SOURCE=200112L -O3 -pthread -DATOMIC equi_miner.cpp blake/blake2b-ref.c -o equi
g++ -m64 -std=c++11 -Wall -Wno-deprecated-declarations -D_POSIX_C_SOURCE=200112L -O3 -pthread equi_miner.cpp blake/blake2b-ref.c -o equi1
g++ -g equi.c blake/blake2b-ref.c -o verify
equi.c: In function ‘int main(int, char**)’:
equi.c:28:43: error: ‘htole32’ was not declared in this scope
   ((u32 *)headernonce)[32] = htole32(nonce);
                                           ^
*** Error code 1
make: Fatal error: Command failed for target `verify'

It seams that equi and equi1 are compiled but if I perform a test I got Bus Error (core dumped)

Looking for wagner-tree on ("0x...",0) with 10 20-bit digits and 1 threads
Using 2^10 buckets, 145MB of memory, and 1-way blake2b
Digit 0 b0 h0
Bus Error (core dumped)

Here the debug:

gdb equi1
GNU gdb (GDB) 7.6
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "sparc-sun-solaris2.11".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /export/home/sysroot/equihash/equi1...done.
(gdb) run
Starting program: /export/home/sysroot/equihash/equi1 
[Thread debugging using libthread_db enabled]
Looking for wagner-tree on ("0x...",0) with 10 20-bit digits and 1 threads
Using 2^10 buckets, 145MB of memory, and 1-way blake2b
[New Thread 1 (LWP 1)]
[New LWP    2        ]
Digit 0 b0 h0
[New Thread 2 (LWP 2)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 2 (LWP 2)]
0x0000000100003470 in equi::digit1 (this=this@entry=0xffffffff7ffff620, id=<optimized out>) at equi_miner.h:771
771               *x++ = x0[0] ^ x1[0];
(gdb) list
766                 bfull++;
767                 continue;
768               }
769               u64 *x  = (u64 *)heaps.heap1[xorbucketid][xorslot];
770               u64 *x0 = (u64 *)slot0, *x1 = (u64 *)slot1;
771               *x++ = x0[0] ^ x1[0];
772               *x++ = x0[1] ^ x1[1];
773               *x++ = x0[2] ^ x1[2];
774               ((htunit *)x)->tag = tree(bucketid, s0, s1);
775             }

Could you help me, please?

Thanks,
Marco

**Comment by tromp** [comment]
dear Marco,

> I commented the include of endian.h and now I have the errors:

endian.h should be needed to get the declaration of htole32.

> g++ -m64 -std=c++11 -Wall -Wno-deprecated-declarations
> -D_POSIX_C_SOURCE=200112L -O3 -pthread -DATOMIC equi_miner.cpp
> blake/blake2b-ref.c -o equi

Strange that this compiles since equi_miner.cpp calls htole32.
Can you do
  man htole32
and see if it mentions any header file to include?

> g++ -g equi.c blake/blake2b-ref.c -o verify
> equi.c: In function ‘int main(int, char**)’:
> equi.c:28:43: error: ‘htole32’ was not declared in this scope

So you can fix this by including whatever header file equi_miner.cpp uses
to get the declaration.

> Program received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 2 (LWP 2)]
> 0x0000000100003470 in equi::digit1 (this=this@entry=0xffffffff7ffff620, id=)
> at equi_miner.h:771
> 771 *x++ = x0[0] ^ x1[0];

I'm afraid I can't debug that without access to a SPARC machine.

regards,
-John

**Comment by ghost** [comment]
Hi John,
sorry for my mistake, I restart the porting to sparc and now I'm not able to compile also equi. (in the previous version I tried to define the "htole32" with "#define htole32(x) BSWAP_32(x)".

The file "endian.h" is not provided in SunOS for sparc and the "man htole32" say that there is no manual for it.

Thus, I think we can restart to analyze the problem with these problems showed after had commented the include of the "endian.h":

g++ -m64 -std=c++11 -Wall -Wno-deprecated-declarations -D_POSIX_C_SOURCE=200112L -O3 -pthread -DATOMIC equi_miner.cpp blake/blake2b-ref.c -o equi
In file included from equi_miner.h:36:0,
                 from equi_miner.cpp:4:
equi.h: In function ‘void setheader(blake2b_state*, const char*)’:
equi.h:46:29: error: ‘htole32’ was not declared in this scope
   uint32_t le_N = htole32(WN);
                             ^
equi.h: In function ‘void genhash(const blake2b_state*, u32, uchar*)’:
equi.h:72:41: error: ‘htole32’ was not declared in this scope
   u32 leb = htole32(idx / HASHESPERBLAKE);
                                         ^
In file included from equi_miner.cpp:4:0:
equi_miner.h: In member function ‘void equi::digit0(u32)’:
equi_miner.h:608:30: error: ‘htole32’ was not declared in this scope
       u32 leb = htole32(block);
                              ^
equi_miner.h: In member function ‘void equi::digit1(u32)’:
equi_miner.h:763:43: error: ‘htobe32’ was not declared in this scope
         cd.addslot(s1, htobe32(slot1->word) >> 20 & 0x3ff);
                                           ^
equi_miner.h: In member function ‘void equi::digit2(u32)’:
equi_miner.h:796:43: error: ‘htobe32’ was not declared in this scope
         cd.addslot(s1, htobe32(slot1->word) & 0x3ff);
                                           ^
equi_miner.h: In member function ‘void equi::digit3(u32)’:
equi_miner.h:830:43: error: ‘htobe32’ was not declared in this scope
         cd.addslot(s1, htobe32(slot1->word) >> 12 & 0x3ff);
                                           ^
equi_miner.h: In member function ‘void equi::digit4(u32)’:
equi_miner.h:872:66: error: ‘htobe32’ was not declared in this scope
           u32 xorbucketid = htobe32(slot0[1].word ^ slot1[1].word) >> 14 & BUCKMASK;
                                                                  ^
equi_miner.h: In member function ‘void equi::digit5(u32)’:
equi_miner.h:896:43: error: ‘htobe32’ was not declared in this scope
         cd.addslot(s1, htobe32(slot1->word) >> 4 & 0x3ff);
                                           ^
equi_miner.h: In member function ‘void equi::digit6(u32)’:
equi_miner.h:930:43: error: ‘htobe32’ was not declared in this scope
         cd.addslot(s1, htobe32(slot1->word) >> 16 & 0x3ff);
                                           ^
equi_miner.h: In member function ‘void equi::digit7(u32)’:
equi_miner.h:973:41: error: ‘htobe32’ was not declared in this scope
           u32 xorbucketid = htobe32(xor1) >> 18 & BUCKMASK;
                                         ^
equi_miner.h: In member function ‘void equi::digit8(u32)’:
equi_miner.h:996:43: error: ‘htobe32’ was not declared in this scope
         cd.addslot(s1, htobe32(slot1->word) >> 8 & 0x3ff);
                                           ^
equi_miner.cpp: In function ‘int main(int, char**)’:
equi_miner.cpp:81:47: error: ‘htole32’ was not declared in this scope
     ((u32 *)headernonce)[32] = htole32(nonce+r);
                                               ^
*** Error code 1
make: Fatal error: Command failed for target `equi'

Thanks,
Marco

**Comment by tromp** [comment]
dear Marco,

> sorry for my mistake, I restart the porting to sparc and now I'm not able to
> compile also equi. (in the previous version I tried to define the "htole32"
> with "#define htole32(x) BSWAP_32(x)".
>
> The file "endian.h" is not provided in SunOS for sparc and the "man htole32"
> say that there is no manual for it.

Then you can add your own version of endian.h,
and include it with #include "endian.h" instead of #include <endian.h>
You can put that
  #define htole32(x) BSWAP_32(x)
in there, together with
  #define htobe32(x) (x)
assuming SPARC is big endian.

regards,
-John

**Comment by ghost** [comment]
Dear John,
thanks for your help. I created a file "endian.h" with there lines:

#include <sys/byteorder.h>

#define htole32(x) BSWAP_32(x)
#define htobe32(x) (x)

and compiled the source adding the "-g" flag for including the debug info. Now I have these errors during the test step:

make test
time ./equi1 -h "" -n 0 -t 1 -s | grep ^Sol | ./verify -h "" -n 0
Verifying size 512 proof for equi("",0)
sh: 9352: Bus error(coredump)

real    0m2.54s
user    0m0.68s
sys     0m0.10s

Using the debugger I see:
gdb ./equi1 
GNU gdb (GDB) 7.6
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "sparc-sun-solaris2.11".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /export/home/sysroot/equihash/equi1...done.
(gdb) run -h "" -n 0 -t 1 -s
Starting program: /export/home/sysroot/equihash/equi1 -h "" -n 0 -t 1 -s
[Thread debugging using libthread_db enabled]
Looking for wagner-tree on ("0x...",0) with 10 20-bit digits and 1 threads
Using 2^10 buckets, 145MB of memory, and 1-way blake2b
[New Thread 1 (LWP 1)]
[New LWP    2        ]
Digit 0 b0 h0
[New Thread 2 (LWP 2)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 2 (LWP 2)]
0x00000001000034f0 in equi::digit1 (this=this@entry=0xffffffff7ffff6f0, id=<optimized out>) at equi_miner.h:779
779               *x++ = x0[0] ^ x1[0];
(gdb) list
774                 bfull++;
775                 continue;
776               }
777               u64 *x  = (u64 *)heaps.heap1[xorbucketid][xorslot];
778               u64 *x0 = (u64 *)slot0, *x1 = (u64 *)slot1;
779               *x++ = x0[0] ^ x1[0];
780               *x++ = x0[1] ^ x1[1];
781               *x++ = x0[2] ^ x1[2];
782               ((htunit *)x)->tag = tree(bucketid, s0, s1);
783             }

Thanks,
Marco

**Comment by tromp** [comment]
dear Marco,

> Program received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 2 (LWP 2)]
> 0x00000001000034f0 in equi::digit1 (this=this@entry=0xffffffff7ffff6f0, id=)
> at equi_miner.h:779
> 779 *x++ = x0[0] ^ x1[0];

Like I said, I would need access to a SPARC machine to debug this...

regards,
-John

**Comment by ghost** [comment]
I know... well my server is not reachable from Internet. I will check if the same problem is reproducible on SunOS for x86 and I will let you know or if you like you can give me the way to debug it.

Regards,
Marco

**Comment by ghost** [comment]
Hi John,
on Solaris for x86 it works :( 
Thus the error is only on sparc (big endian)
I hope you could help me

**Comment by tromp** [comment]
dear Marco,

> Thus the error is only on sparc (big endian)
> I hope you could help me

Can you arrange any Sparc server in the cloud that I could access?

regards,
-John

**Comment by ghost** [comment]
Hi John,
sorry for my long delay. The server was not accessible from Internet. Anyway I stopped the porting because this server was reused for other project so it's not yet available.

Thanks anyway.

Regards,
Marco
