### ISSUE TITLE
Passing header parameter -  Help needed

### ISSUE THREAD

**Issue by ghost** [tromp/equihash#12]
Hi John,

I would like to ask if you could please help me to understand how to create the header parameter starting from my data:

- Pubkey
- pszTimestamp
- TX/merkle root hash
- Unix Time

I need to generate the genisis block on my regtest based on equihash 48,5 using your utility eq4851

Thanks,
Marco

**Comment by tromp** [comment]
dear Marco,

> I would like to ask if you could please help me to understand how to create
> the header parameter starting from my data:
>
> Pubkey
> pszTimestamp
> TX/merkle root hash
> Unix Time
>
> I need to generate the genisis block on my regtest based on equihash 48,5
> using your utility eq4851

This is somewhat outside the scope of the solver and depends on the
particulars of the blockchain
you're using Equihash for. Zcash specified a certain initialization
for blake2b as implemented in my setheader():

void setheader(blake2b_state *ctx, const char *headernonce) {
  uint32_t le_N = htole32(WN);
  uint32_t le_K = htole32(WK);
  uchar personal[] = "ZcashPoW01230123";
  memcpy(personal+8,  &le_N, 4);
  memcpy(personal+12, &le_K, 4);
  blake2b_param P[1];
  P->digest_length = HASHOUT;
  P->key_length    = 0;
  P->fanout        = 1;
  P->depth         = 1;
  P->leaf_length   = 0;
  P->node_offset   = 0;
  P->node_depth    = 0;
  P->inner_length  = 0;
  memset(P->reserved, 0, sizeof(P->reserved));
  memset(P->salt,     0, sizeof(P->salt));
  memcpy(P->personal, (const uint8_t *)personal, 16);
  blake2b_init_param(ctx, P);
  blake2b_update(ctx, (const uchar *)headernonce, HEADERNONCELEN);
}

The last line process the entire header of 140 bytes including the
fields you mention and the nonce.
My solver is not concerned with how these fields are laid out. All it
knows about the header is that
the 4 bytes at 128..131 are part of the nonce field and can be varied
as in line 81 of
equi_miner.cpp

regards,
-John
