### ISSUE TITLE
Use solver with N=96,K=5

### ISSUE THREAD

**Issue by mikebzh44** [tromp/equihash#13]
Hello.

Sorry to open an issue for that because it's more a question.

I'm looking for a CUDA optimized miner for Minexcoin.

Can you confirm that you solver can run with N=96,K=5 which is the Mars algo used by Minexcoin ?

Your solver is used by nheqminer. How can I force nheqminer to use your solver with those parameters ?

I hope you can help me.

Thanks.

**Comment by tromp** [comment]
hi Mikael,

> Sorry to open an issue for that because it's more a question.
>
> I'm looking for a CUDA optimized miner for Minexcoin.
>
> Can you confirm that you solver can run with N=96,K=5 which is the Mars algo
> used by Minexcoin ?

Sure. just compile with
-DRESTBITS=4 -DWN=96 -DWK=5
and then e.g.

$ time ./eq965 -s
Looking for wagner-tree on ("0x...",0) with 6 16-bit digits and 1 threads
Using 2^12 buckets, 9MB of memory, and 1-way blake2b
Digit 0 b0 h0
Digit 1 b0 h0
Digit 2 b0 h0
Digit 3 b0 h3
Digit 4 b0 h4
Digit 5
Solution 1c0 39b3 9c6a 1bcc1 7377 82cd 96f1 b77b 2df3 4c30 a082 1cb90
3472 155b7 f0d4 1b0e8 7df 1ad14 abdf fc89 18a69 1d18d 19385 1976f 1e47
fac8 2481 12787 8bfa 18422 f3da 1a6e1
1 solutions
1 total solutions

real 0m0.034s
user 0m0.024s
sys 0m0.006s

> Your solver is used by nheqminer. How can I force nheqminer to use your
> solver with those parameters ?

No idea; I never studied their miner adaptations.
Try identify where they set the above 3 defines in their build.

regards,
-John

**Comment by mikebzh44** [comment]
Thanks

I will have a look this weekend ;)
