### ISSUE TITLE
documentation options

### ISSUE THREAD

**Issue by madtomic** [tromp/equihash#14]
Can you please provide better documentation on the options for the solver?

what are -p, -s and -x? I might missed some.

../equihash/equi1 -p 34 -s -n 302317566 -r 9 -x

The only thing I found are these.

Options -h HEADER -n NONCE are self explanatory. Add option -r RANGESIZE to search a range of nonces. For benching, options -n 255 -r 100 are useful as it gets exactly 188 solutions from 100 runs.

**Comment by tromp** [comment]
README updated to explain options -s and -x
There is no option -p

**Comment by madtomic** [comment]
Thank you kindly
