### ISSUE TITLE
Why isn't this array access out of bound?

### ISSUE THREAD

**Issue by sebastianst** [tromp/equihash#15]
I'm trying to understand some part of the solver and am stuck here.
See
https://github.com/tromp/equihash/blob/39a91772abc503ace4b5ae5e1af1fde482eb077b/equi_miner.h#L908
`digit4()` and `digit7()` both access `slot1->bytes[4]`, but the union `slot1`, which is a `htunit`, holds at `bytes` a   `uchar[sizeof(tree_t)]` presentation. `tree_t` is either `u16` or `u32`, so `sizeof(tree_t)` is either 2 or 4. How can the access to `bytes[4]` not be out of the array's bound?

**Comment by tromp** [comment]
Slots are in fact larger than a single htunit:

typedef htunit slot0[HASHWORDS0+1];
typedef htunit slot1[HASHWORDS1+1];

So the bytes[] in one htunit can extend into subsequent htunits.
Also see the slot layout on lines 280-288 showing how slots for different rounds overlap.

**Comment by sebastianst** [comment]
Doh, didn't see it was a `htunit[]` array, sorry!
