### ISSUE TITLE
Vary blake2b 'personal' bytes from command line

### ISSUE THREAD

**Issue by tearodactyl** [tromp/equihash#19]
More recent Zcash clones have been modifying first five characters of the 16 byte blake2b personal string of which Zcash sets initial eight to "ZcashPoW". Some examples are:
Bitcoin Gold (BTG) "Bgold"
Snowgem (XSG) "sngem"
Zero Currency (ZERO) "Zero_"

This became particularly important with the recent 51% attacks. It would be very helpful for the developers if the contents of these first five or of eight characters could be optionally passed on command line.

**Comment by tromp** [comment]
implemented for plain CPU miners with option -p
