### ISSUE TITLE
Help regarding which nonce to try and how to check the difficulty

### ISSUE THREAD

**Issue by mwyborski** [tromp/equihash#21]
Dear Mr Tromp,
i downloaded your code and would like to build my own miner from it. I just started to get into Equihash and found a great explanation on how it is working here: 
https://forum.zcashcommunity.com/t/easy-to-follow-description-of-the-equihash-algorithm/12689
This already explained a lot to me in combination with your solver. But now i am a stuck on how to calculate the nonce_2 for pool mining or the whole nonce for solo mining.  I know, that this might be out of the scope of your solver, but as you seem professional in this topic, i thought i just try to ask you :-)

Specifically i would like to know, how to calculate the difficulty with the double sha256 checksum over the total block and how to compare it to the target, to know if it fulfills the difficulty criteria? Also i would like to know, how do i find out, which nonce i should try? I am using the 144 5 variant for btg.

In your other post https://github.com/tromp/equihash/issues/1 you wrote that the solver by itself tries a range of nonce. Does that mean, that i get also solutions for another nonce than the 32-byte one that i pass in the header? Is it possible to print out the nonce, that is used for a solution?

I would greatly appreciate any hints from you.
BR
Marek

**Comment by tromp** [comment]
That is indeed out of scope of my solvers, which (falsely) assume that the nonce is only 4 bytes and occupied bytes 108-111 of the header. My solvers are neither concerned with difficulty computations.

> Does that mean, that i get also solutions for another nonce than the 32-byte one that i pass in the header?

Yes; you can trivially change the code to print out the nonce used (nonce+r) together with every Solution in line 126.

**Comment by mwyborski** [comment]
Ok. Thank you for clearing this up! Anyways your code is a great help in understanding wagners algorithm.
