### ISSUE TITLE
memset bug

### ISSUE THREAD

**Issue by nicehashdev** [tromp/equihash#8]
https://github.com/tromp/equihash/blob/master/equi_miner.cu#L183

Shouldn't it be 2 * NBUCKETS ?

Btw, there is still some bug in your CUDA implementation that sometimes produces an invalid solution. Are you aware of it?

**Comment by tromp** [comment]
> https://github.com/tromp/equihash/blob/master/equi_miner.cu#L183
> 
> Shouldn't it be 2 \* NBUCKETS ?

Actually, it should be 0 \* NBUCKETS :-)

That whole memset is redundant now, since nslots[0] and nslots[1]
were originally allocated with calloc, and digitK() clears the remaining
non-zero entries in nslots[0] through its getnslots0() calls.

I've just committed a new version reflecting this...

regards,
-John

**Comment by tromp** [comment]
> > https://github.com/tromp/equihash/blob/master/equi_miner.cu#L183
> > 
> > Shouldn't it be 2 \* NBUCKETS ?
> 
> Actually, it should be 0 \* NBUCKETS :-)
> 
> That whole memset is redundant now, since nslots[0] and nslots[1]
> were originally allocated with calloc, and digitK() clears the remaining

While that is true for the CPU version, I see that the CUDA code
uses a malloc that doesn't clear the memory. So you're right that we
need to clear the whole array there. Thanks for pointing out that bug!
I'll put up a fix in a few minutes.

**Comment by nicehashdev** [comment]
Any hints where that other bug may be located? Sometimes, solution is invalid and this always happen after several seconds when mining starts... (using your solution validator).

**Comment by tromp** [comment]
> Any hints where that other bug may be located? Sometimes, solution is
> invalid and this always happen after several seconds when mining starts...
> (using your solution validator).

What other bug? You just pointed out the lack of nslots clearing in my
CUDA code and I just fixed it. Do you still see invalid solutions with
my latest commit?

**Comment by nicehashdev** [comment]
Yes, this bug of not clearing bucket sizes is not related. I may catch a solution that gets through your CUDA code ok? Will do it in next days and report.

**Comment by tromp** [comment]
> Yes, this bug of not clearing bucket sizes is not related. I may catch a solution that gets through your CUDA code ok? Will do it in next days and report.

Yes, please report on any other sign of buggy behaviour. Thanks!

**Comment by nicehashdev** [comment]
I just stumbled across something while writing optimised CUDA probdupe kernel.

https://github.com/tromp/equihash/blob/master/equi_miner.cu#L320

Is it possible, that the source of invalid solutions may be in here? If I understand correctly, this method is not fully exact and can sometimes permit invalid solutions to go through?

**Comment by tromp** [comment]
> I just stumbled across something while writing optimised CUDA probdupe kernel.
> 
> https://github.com/tromp/equihash/blob/master/equi_miner.cu#L320
> 
> Is it possible, that the source of invalid solutions may be in here? If I understand correctly, this method is not fully exact and can sometimes permit invalid solutions to go through?

Yes, you understand correctly. That's why my main() in equi_miner.cu has

```
for (s = nsols = 0; s < maxsols; s++) {
  if (duped(sols[s])) {
    printf("Duped!\n");
    continue;
  }
```

to fully check all returned solutions to filter out the bad ones.

regards,
-John

**Comment by nicehashdev** [comment]
Thanks! Solved the issue, now miner is superb with 0 rejects 👍
