### ISSUE TITLE
solver 100% CPU core with nvidia

### ISSUE THREAD

**Issue by montvid** [tromp/equihash#9]
I use nheqminer with your nvidia cuda code. When I load 1 instance i get a 100% cpu load in 1 of 4 cpu's. People are discussing a solution to get it down with good results here [https://github.com/mbevand/silentarmy/issues/54](url)
Your nvidia cuda implementation is quite good so it would be nice to have an update. :)

**Comment by tromp** [comment]
> I use nheqminer with your nvidia cuda code. When I load 1 instance i get a 100% cpu load in 1 of 4 cpu's. People are discussing a solution to get it down with good results here https://github.com/mbevand/silentarmy/issues/54

Aren't you confusing my cuda solver with Marc's silentarmy one?

-John

**Comment by montvid** [comment]
Your 1 cuda solver brings 1 cpu core to 100% does it not? Is it just nheqminer implementation?

**Comment by montvid** [comment]
I use your cuda solver in nheqminer. No, I am not confusing them.

**Comment by tromp** [comment]
> Your 1 cuda solver brings 1 cpu core to 100% does it not? Is it just nheqminer implementation?

Let me check...

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+
COMMAND
11208 tromp     20   0 36.314g  93124  81852 R 100.3  0.6   0:18.43
eqcuda
Yes, 100% cpu.
Sorry for misunderstanding the role of Marc miner in your firs post.
Let me digest Marc's thread and see if that applies to mine as well...

regards,
-John

**Comment by tromp** [comment]
> Sorry for misunderstanding the role of Marc miner in your firs post.
> Let me digest Marc's thread and see if that applies to mine as well...

I see some suggestions for openCL but none for CUDA
(except a broken link from https://devtalk.nvidia.com/default/topic/494659/execute-kernels-without-100-cpu-busy-wait-/ to http://www.khronos.org/message_boards/viewtopic.php?f=28&t=2798)

**Comment by montvid** [comment]
The code in the thread solves the issue for silentarmy's nvidia gpu solver. I thought it might solve your nvidia gpu solver's problem too. Oh well, sorry if I misunderstood. :) So silentarmy's nvidia gpu solver uses opencl and your nvidia gpu solver uses cuda?
https://bitcointalk.org/index.php?topic=1666489.msg16818120#msg16818120

https://github.com/mbevand/silentarmy/pull/60/files

**Comment by tromp** [comment]
> The code in the thread solves the issue for silentarmy's nvidia gpu solver. I thought it might solve your nvidia gpu solver's problem too. Oh well, sorry if I misunderstood. :) So silentarmy's nvidia gpu solver uses opencl and your nvidia gpu solver uses cuda?

Yes; please let me know if you see a busy waiting solution in CUDA. Thanks.
